/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shopapp;

/**
 *
 * @author canno
 */
public class ShopUI extends javax.swing.JFrame {

    /**
     * Creates new form ShopUI
     */
    public ShopUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundJP = new javax.swing.JPanel();
        itembg1JP = new javax.swing.JPanel();
        item1LBL = new javax.swing.JLabel();
        price1LBL = new javax.swing.JLabel();
        image1LBL = new javax.swing.JLabel();
        remove1BTN = new javax.swing.JButton();
        buy1BTN = new javax.swing.JButton();
        stock1LBL = new javax.swing.JLabel();
        itembg2JP = new javax.swing.JPanel();
        item2LBL = new javax.swing.JLabel();
        price2LBL = new javax.swing.JLabel();
        image2LBL = new javax.swing.JLabel();
        buy2BTN = new javax.swing.JButton();
        remove2BTN = new javax.swing.JButton();
        stock2LBL = new javax.swing.JLabel();
        itembg5JP = new javax.swing.JPanel();
        item5LBL = new javax.swing.JLabel();
        price5LBL = new javax.swing.JLabel();
        image5LBL = new javax.swing.JLabel();
        remove5BTN = new javax.swing.JButton();
        buy5BTN = new javax.swing.JButton();
        stock5LBL = new javax.swing.JLabel();
        itembg6JP = new javax.swing.JPanel();
        price6LBL = new javax.swing.JLabel();
        item6LBL = new javax.swing.JLabel();
        image6LBL = new javax.swing.JLabel();
        remove6BTN = new javax.swing.JButton();
        buy6BTN = new javax.swing.JButton();
        stock6LBL = new javax.swing.JLabel();
        itembg4JP = new javax.swing.JPanel();
        price4BL = new javax.swing.JLabel();
        item4LBL = new javax.swing.JLabel();
        image4LBL = new javax.swing.JLabel();
        buy4BTN = new javax.swing.JButton();
        remove4BTN = new javax.swing.JButton();
        stock4LBL = new javax.swing.JLabel();
        itembg3JP = new javax.swing.JPanel();
        price3LBL = new javax.swing.JLabel();
        item3LBL = new javax.swing.JLabel();
        image3LBL = new javax.swing.JLabel();
        buy3BTN = new javax.swing.JButton();
        remove3BTN = new javax.swing.JButton();
        stock3LBL = new javax.swing.JLabel();
        basketJP = new javax.swing.JPanel();
        basketLBL = new javax.swing.JLabel();
        totalLBL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nameLBL = new javax.swing.JLabel();
        emailLBL = new javax.swing.JLabel();
        addressLBL = new javax.swing.JLabel();
        billinginfoLBL = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTA = new javax.swing.JTextArea();
        checkoutBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BackgroundJP.setBackground(new java.awt.Color(49, 122, 139));
        BackgroundJP.setMaximumSize(new java.awt.Dimension(1500, 800));
        BackgroundJP.setMinimumSize(new java.awt.Dimension(1500, 800));
        BackgroundJP.setPreferredSize(new java.awt.Dimension(1500, 800));

        itembg1JP.setBackground(new java.awt.Color(0, 255, 255));
        itembg1JP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        item1LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        item1LBL.setText("AquaGuard Shirt");

        price1LBL.setText("Price: €20.99");

        image1LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopapp/tshirt.png"))); // NOI18N

        remove1BTN.setBackground(new java.awt.Color(1, 187, 187));
        remove1BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        remove1BTN.setForeground(new java.awt.Color(255, 255, 255));
        remove1BTN.setText("Remove");
        remove1BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        buy1BTN.setBackground(new java.awt.Color(1, 187, 187));
        buy1BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buy1BTN.setForeground(new java.awt.Color(255, 255, 255));
        buy1BTN.setText("Buy");
        buy1BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        stock1LBL.setText("Stock : 10");

        javax.swing.GroupLayout itembg1JPLayout = new javax.swing.GroupLayout(itembg1JP);
        itembg1JP.setLayout(itembg1JPLayout);
        itembg1JPLayout.setHorizontalGroup(
            itembg1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itembg1JPLayout.createSequentialGroup()
                .addGroup(itembg1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itembg1JPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(itembg1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itembg1JPLayout.createSequentialGroup()
                                .addComponent(item1LBL)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(itembg1JPLayout.createSequentialGroup()
                                .addGroup(itembg1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price1LBL)
                                    .addComponent(stock1LBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(buy1BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(remove1BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(itembg1JPLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(image1LBL)))
                .addContainerGap())
        );
        itembg1JPLayout.setVerticalGroup(
            itembg1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itembg1JPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image1LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item1LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stock1LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(itembg1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy1BTN)
                    .addComponent(remove1BTN)
                    .addComponent(price1LBL))
                .addGap(8, 8, 8))
        );

        itembg2JP.setBackground(new java.awt.Color(0, 255, 255));
        itembg2JP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        item2LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        item2LBL.setText("AquaGuard Cap");

        price2LBL.setText("Price: €20.99");

        image2LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopapp/cap.png"))); // NOI18N

        buy2BTN.setBackground(new java.awt.Color(1, 187, 187));
        buy2BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buy2BTN.setForeground(new java.awt.Color(255, 255, 255));
        buy2BTN.setText("Buy");
        buy2BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        remove2BTN.setBackground(new java.awt.Color(1, 187, 187));
        remove2BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        remove2BTN.setForeground(new java.awt.Color(255, 255, 255));
        remove2BTN.setText("Remove");
        remove2BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        stock2LBL.setText("Stock : 10");

        javax.swing.GroupLayout itembg2JPLayout = new javax.swing.GroupLayout(itembg2JP);
        itembg2JP.setLayout(itembg2JPLayout);
        itembg2JPLayout.setHorizontalGroup(
            itembg2JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itembg2JPLayout.createSequentialGroup()
                .addGroup(itembg2JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itembg2JPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(itembg2JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itembg2JPLayout.createSequentialGroup()
                                .addComponent(item2LBL)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(itembg2JPLayout.createSequentialGroup()
                                .addGroup(itembg2JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price2LBL)
                                    .addComponent(stock2LBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(buy2BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(remove2BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(itembg2JPLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(image2LBL)))
                .addContainerGap())
        );
        itembg2JPLayout.setVerticalGroup(
            itembg2JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itembg2JPLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(image2LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item2LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stock2LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itembg2JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy2BTN)
                    .addComponent(remove2BTN)
                    .addComponent(price2LBL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itembg5JP.setBackground(new java.awt.Color(0, 255, 255));
        itembg5JP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        item5LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        item5LBL.setText("AquaGuard Poster");

        price5LBL.setText("Price: €20.99");

        image5LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopapp/poster.png"))); // NOI18N

        remove5BTN.setBackground(new java.awt.Color(1, 187, 187));
        remove5BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        remove5BTN.setForeground(new java.awt.Color(255, 255, 255));
        remove5BTN.setText("Remove");
        remove5BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        buy5BTN.setBackground(new java.awt.Color(1, 187, 187));
        buy5BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buy5BTN.setForeground(new java.awt.Color(255, 255, 255));
        buy5BTN.setText("Buy");
        buy5BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        stock5LBL.setText("Stock : 10");

        javax.swing.GroupLayout itembg5JPLayout = new javax.swing.GroupLayout(itembg5JP);
        itembg5JP.setLayout(itembg5JPLayout);
        itembg5JPLayout.setHorizontalGroup(
            itembg5JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itembg5JPLayout.createSequentialGroup()
                .addGroup(itembg5JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itembg5JPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(price5LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buy5BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(remove5BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itembg5JPLayout.createSequentialGroup()
                        .addGroup(itembg5JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itembg5JPLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(image5LBL))
                            .addGroup(itembg5JPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(item5LBL)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(itembg5JPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stock5LBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itembg5JPLayout.setVerticalGroup(
            itembg5JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itembg5JPLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(image5LBL)
                .addGap(7, 7, 7)
                .addComponent(item5LBL)
                .addGap(9, 9, 9)
                .addComponent(stock5LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(itembg5JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(price5LBL)
                    .addComponent(buy5BTN)
                    .addComponent(remove5BTN))
                .addContainerGap())
        );

        itembg6JP.setBackground(new java.awt.Color(0, 255, 255));
        itembg6JP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        price6LBL.setText("Price: €20.99");

        item6LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        item6LBL.setText("AquaGuard Plush");

        image6LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopapp/plush.png"))); // NOI18N

        remove6BTN.setBackground(new java.awt.Color(1, 187, 187));
        remove6BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        remove6BTN.setForeground(new java.awt.Color(255, 255, 255));
        remove6BTN.setText("Remove");
        remove6BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        buy6BTN.setBackground(new java.awt.Color(1, 187, 187));
        buy6BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buy6BTN.setForeground(new java.awt.Color(255, 255, 255));
        buy6BTN.setText("Buy");
        buy6BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        stock6LBL.setText("Stock : 10");

        javax.swing.GroupLayout itembg6JPLayout = new javax.swing.GroupLayout(itembg6JP);
        itembg6JP.setLayout(itembg6JPLayout);
        itembg6JPLayout.setHorizontalGroup(
            itembg6JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itembg6JPLayout.createSequentialGroup()
                .addGroup(itembg6JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itembg6JPLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(image6LBL))
                    .addGroup(itembg6JPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(itembg6JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itembg6JPLayout.createSequentialGroup()
                                .addComponent(price6LBL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(buy6BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(remove6BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(itembg6JPLayout.createSequentialGroup()
                                .addComponent(item6LBL)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(itembg6JPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stock6LBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itembg6JPLayout.setVerticalGroup(
            itembg6JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itembg6JPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image6LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item6LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stock6LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(itembg6JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buy6BTN)
                    .addComponent(remove6BTN)
                    .addComponent(price6LBL))
                .addContainerGap())
        );

        itembg4JP.setBackground(new java.awt.Color(0, 255, 255));
        itembg4JP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        price4BL.setText("Price: €20.99");

        item4LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        item4LBL.setText("AquaGuard Bracelet");

        image4LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopapp/bracelet.png"))); // NOI18N
        image4LBL.setText(".");

        buy4BTN.setBackground(new java.awt.Color(1, 187, 187));
        buy4BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buy4BTN.setForeground(new java.awt.Color(255, 255, 255));
        buy4BTN.setText("Buy");
        buy4BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        remove4BTN.setBackground(new java.awt.Color(1, 187, 187));
        remove4BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        remove4BTN.setForeground(new java.awt.Color(255, 255, 255));
        remove4BTN.setText("Remove");
        remove4BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        stock4LBL.setText("Stock : 10");

        javax.swing.GroupLayout itembg4JPLayout = new javax.swing.GroupLayout(itembg4JP);
        itembg4JP.setLayout(itembg4JPLayout);
        itembg4JPLayout.setHorizontalGroup(
            itembg4JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itembg4JPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(itembg4JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itembg4JPLayout.createSequentialGroup()
                        .addGroup(itembg4JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item4LBL)
                            .addComponent(stock4LBL))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itembg4JPLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(image4LBL))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itembg4JPLayout.createSequentialGroup()
                        .addComponent(price4BL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buy4BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(remove4BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        itembg4JPLayout.setVerticalGroup(
            itembg4JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itembg4JPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(image4LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item4LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stock4LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(itembg4JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(itembg4JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buy4BTN)
                        .addComponent(price4BL))
                    .addComponent(remove4BTN))
                .addContainerGap())
        );

        itembg3JP.setBackground(new java.awt.Color(0, 255, 255));
        itembg3JP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        price3LBL.setText("Price: €20.99");

        item3LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        item3LBL.setText("AquaGuard Bottle");

        image3LBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopapp/bottle.png"))); // NOI18N

        buy3BTN.setBackground(new java.awt.Color(1, 187, 187));
        buy3BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buy3BTN.setForeground(new java.awt.Color(255, 255, 255));
        buy3BTN.setText("Buy");
        buy3BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        remove3BTN.setBackground(new java.awt.Color(1, 187, 187));
        remove3BTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        remove3BTN.setForeground(new java.awt.Color(255, 255, 255));
        remove3BTN.setText("Remove");
        remove3BTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));

        stock3LBL.setText("Stock : 10");

        javax.swing.GroupLayout itembg3JPLayout = new javax.swing.GroupLayout(itembg3JP);
        itembg3JP.setLayout(itembg3JPLayout);
        itembg3JPLayout.setHorizontalGroup(
            itembg3JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itembg3JPLayout.createSequentialGroup()
                .addGroup(itembg3JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itembg3JPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(itembg3JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stock3LBL)
                            .addComponent(price3LBL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buy3BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(remove3BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(itembg3JPLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(image3LBL)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(itembg3JPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(item3LBL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itembg3JPLayout.setVerticalGroup(
            itembg3JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itembg3JPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image3LBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(item3LBL)
                .addGroup(itembg3JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itembg3JPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(itembg3JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buy3BTN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(remove3BTN, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(itembg3JPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stock3LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price3LBL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        basketJP.setBackground(new java.awt.Color(33, 86, 138));
        basketJP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        basketLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        basketLBL.setForeground(new java.awt.Color(255, 255, 255));
        basketLBL.setText("Basket");

        totalLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        totalLBL.setForeground(new java.awt.Color(255, 255, 255));
        totalLBL.setText("Total:");

        javax.swing.GroupLayout basketJPLayout = new javax.swing.GroupLayout(basketJP);
        basketJP.setLayout(basketJPLayout);
        basketJPLayout.setHorizontalGroup(
            basketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basketJPLayout.createSequentialGroup()
                .addGroup(basketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basketJPLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(basketLBL))
                    .addGroup(basketJPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(totalLBL)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        basketJPLayout.setVerticalGroup(
            basketJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basketJPLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(basketLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalLBL)
                .addGap(14, 14, 14))
        );

        jPanel1.setBackground(new java.awt.Color(33, 86, 138));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        nameLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nameLBL.setForeground(new java.awt.Color(255, 255, 255));
        nameLBL.setText("Name:");

        emailLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailLBL.setForeground(new java.awt.Color(255, 255, 255));
        emailLBL.setText("Email:");

        addressLBL.setBackground(new java.awt.Color(255, 255, 255));
        addressLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addressLBL.setForeground(new java.awt.Color(255, 255, 255));
        addressLBL.setText("Address:");

        billinginfoLBL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        billinginfoLBL.setForeground(new java.awt.Color(255, 255, 255));
        billinginfoLBL.setText("Billing Information");

        addressTA.setColumns(20);
        addressTA.setRows(5);
        jScrollPane1.setViewportView(addressTA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addressLBL)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailLBL, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(nameLBL)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTF)
                                    .addComponent(emailTF)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(billinginfoLBL)))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billinginfoLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLBL)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLBL))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addressLBL))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        checkoutBTN.setBackground(new java.awt.Color(1, 187, 187));
        checkoutBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        checkoutBTN.setForeground(new java.awt.Color(255, 255, 255));
        checkoutBTN.setText("Checkout");
        checkoutBTN.setToolTipText("");
        checkoutBTN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        javax.swing.GroupLayout BackgroundJPLayout = new javax.swing.GroupLayout(BackgroundJP);
        BackgroundJP.setLayout(BackgroundJPLayout);
        BackgroundJPLayout.setHorizontalGroup(
            BackgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundJPLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(BackgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itembg1JP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itembg4JP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(BackgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itembg2JP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itembg5JP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(BackgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itembg3JP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itembg6JP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(BackgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(basketJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        BackgroundJPLayout.setVerticalGroup(
            BackgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundJPLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(BackgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itembg1JP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itembg2JP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itembg3JP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basketJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(BackgroundJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackgroundJPLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkoutBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(itembg6JP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itembg5JP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itembg4JP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundJP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundJP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundJP;
    private javax.swing.JLabel addressLBL;
    private javax.swing.JTextArea addressTA;
    private javax.swing.JPanel basketJP;
    private javax.swing.JLabel basketLBL;
    private javax.swing.JLabel billinginfoLBL;
    private javax.swing.JButton buy1BTN;
    private javax.swing.JButton buy2BTN;
    private javax.swing.JButton buy3BTN;
    private javax.swing.JButton buy4BTN;
    private javax.swing.JButton buy5BTN;
    private javax.swing.JButton buy6BTN;
    private javax.swing.JButton checkoutBTN;
    private javax.swing.JLabel emailLBL;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel image1LBL;
    private javax.swing.JLabel image2LBL;
    private javax.swing.JLabel image3LBL;
    private javax.swing.JLabel image4LBL;
    private javax.swing.JLabel image5LBL;
    private javax.swing.JLabel image6LBL;
    private javax.swing.JLabel item1LBL;
    private javax.swing.JLabel item2LBL;
    private javax.swing.JLabel item3LBL;
    private javax.swing.JLabel item4LBL;
    private javax.swing.JLabel item5LBL;
    private javax.swing.JLabel item6LBL;
    private javax.swing.JPanel itembg1JP;
    private javax.swing.JPanel itembg2JP;
    private javax.swing.JPanel itembg3JP;
    private javax.swing.JPanel itembg4JP;
    private javax.swing.JPanel itembg5JP;
    private javax.swing.JPanel itembg6JP;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel price1LBL;
    private javax.swing.JLabel price2LBL;
    private javax.swing.JLabel price3LBL;
    private javax.swing.JLabel price4BL;
    private javax.swing.JLabel price5LBL;
    private javax.swing.JLabel price6LBL;
    private javax.swing.JButton remove1BTN;
    private javax.swing.JButton remove2BTN;
    private javax.swing.JButton remove3BTN;
    private javax.swing.JButton remove4BTN;
    private javax.swing.JButton remove5BTN;
    private javax.swing.JButton remove6BTN;
    private javax.swing.JLabel stock1LBL;
    private javax.swing.JLabel stock2LBL;
    private javax.swing.JLabel stock3LBL;
    private javax.swing.JLabel stock4LBL;
    private javax.swing.JLabel stock5LBL;
    private javax.swing.JLabel stock6LBL;
    private javax.swing.JLabel totalLBL;
    // End of variables declaration//GEN-END:variables
}
